In [2]:
# 모듈 불러오기
import pandas as pd
from collections import Counter

In [9]:
# 데이터 불러오기
drama = pd.read_excel('./justwatch.xlsx', index_col=0)
drama.head()

,title,original_title,year,season_episode,runtime,genre,age_rating,Production country
0,Ojingeo Geim,Squid Game,2021,2,55min,"액션, 드라마, 스릴러",19,대한민국
1,12인의 심판자,The Twelve,2019,2,54min,"드라마, 스릴러",NaN,벨기에
2,희생자 게임,誰是被害者,2020,2,1시간 0분,"드라마, 범죄, 스릴러",19,대만
3,스위트 투스: 사슴뿔을 가진 소년,Sweet Tooth,2021,3,52min,"SF, 드라마, 판타지, 액션",15,미국
4,Sweet Home,NaN,2020,3,1시간 0분,"스릴러, 드라마, 판타지, 공포, SF, 범죄",NaN,대한민국

In [11]:
# 데이터 살펴보기
drama.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1090 entries, 0 to 1089
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               1090 non-null   object
 1   original_title      855 non-null    object
 2   year                1090 non-null   int64
 3   season_episode      1090 non-null   int64
 4   runtime             1090 non-null   object
 5   genre               1090 non-null   object
 6   age_rating          803 non-null    object
 7   Production country  1089 non-null   object
dtypes: int64(2), object(6)
memory usage: 76.6+ KB

In [13]:
drama[drama['season_episode'] >= 2]

,title,original_title,year,season_episode,runtime,genre,age_rating,Production country
0,Ojingeo Geim,Squid Game,2021,2,55min,"액션, 드라마, 스릴러",19,대한민국
1,12인의 심판자,The Twelve,2019,2,54min,"드라마, 스릴러",NaN,벨기에
2,희생자 게임,誰是被害者,2020,2,1시간 0분,"드라마, 범죄, 스릴러",19,대만
3,스위트 투스: 사슴뿔을 가진 소년,Sweet Tooth,2021,3,52min,"SF, 드라마, 판타지, 액션",15,미국
4,Sweet Home,NaN,2020,3,1시간 0분,"스릴러, 드라마, 판타지, 공포, SF, 범죄",NaN,대한민국
...,...,...,...,...,...,...,...,...
1051,거짓말의 거짓말,Mytho,2019,2,46min,"코미디, 드라마",19,프랑스
1053,헨테파이드,Gentefied,2020,2,30min,"코미디, 드라마",NaN,미국
1062,췌서 : 데릴사위,赘婿,2021,2,44min,"코미디, SF, 드라마, 액션",15+,China
1063,Twenty Your Life On,NaN,2020,2,47min,"로맨스, 드라마",12+,NaN
1080,꽃 같은 내 인생,植劇場 - 花甲男孩轉大人,2017,2,1시간 29분,"드라마, 코미디",15,대만

In [17]:
# 제조 국가
drama['Production country'].value_counts().head(20)

Production country
대한민국        225
미국          213
일본           81
영국           54
China        51
스페인          48
인도           38
대만           30
프랑스          25
멕시코          25
독일           23
터키           22
태국           21
브라질          19
폴란드          17
호주           16
이탈리아         16
캐나다          16
스웨덴          12
남아프리카공화국     11
Name: count, dtype: int64

In [18]:
# 연도
drama['year'].value_counts().head(20)

year
2022    182
2023    159
2021    152
2020    146
2019    134
2018    101
2016     65
2017     65
2015     24
2013     11
2014     10
2011      8
2012      6
2010      4
2005      3
2009      3
2007      3
2008      2
2004      2
2006      2
Name: count, dtype: int64

In [29]:
# 장르
genre = []
for idx, row in drama.iterrows():
    tmp_list= row['genre'].split(', ')
    for x in tmp_list:
        genre.append(x)

In [36]:
counts = Counter(genre)
for element, count in counts.items():
    print(f'{element}: {count}')

액션: 177
드라마: 1090
스릴러: 386
범죄: 287
SF: 194
판타지: 143
공포: 79
전쟁: 33
코미디: 355
Made in Europe: 21
로맨스: 276
역사: 62
음악: 22
가족: 52
스포츠: 15
서부: 5

In [39]:
drama['season_episode'].value_counts()

season_episode
1     752
2     176
3      71
4      36
7      16
5      16
6      13
8       4
9       3
11      1
10      1
17      1
Name: count, dtype: int64

In [40]:
drama[drama['season_episode'] == 17]

,title,original_title,year,season_episode,runtime,genre,age_rating,Production country
60,Heartland,NaN,2007,17,44min,"드라마, 가족, 코미디",12,캐나다

In [41]:
drama[drama['season_episode'] == 11]

,title,original_title,year,season_episode,runtime,genre,age_rating,Production country
7,워킹 데드,The Walking Dead,2010,11,46min,"드라마, SF, 액션, 공포, 스릴러",19,미국

In [42]:
drama[drama['season_episode'] == 10]

,title,original_title,year,season_episode,runtime,genre,age_rating,Production country
24,블랙리스트,The Blacklist,2013,10,43min,"스릴러, 범죄, 드라마",15,미국

In [43]:
drama[drama['season_episode'] == 9]

,title,original_title,year,season_episode,runtime,genre,age_rating,Production country
9,The Flash,NaN,2014,9,45min,"액션, 드라마, SF",15,미국
12,Suits,NaN,2011,9,44min,"코미디, 드라마",15,미국
122,웬트워스,Wentworth,2013,9,46min,"드라마, 범죄, 스릴러",19,호주

In [44]:
drama[drama['season_episode'] == 8]

,title,original_title,year,season_episode,runtime,genre,age_rating,Production country
27,뱀파이어 다이어리,The Vampire Diaries,2009,8,42min,"SF, 판타지, 공포, 로맨스, 스릴러, 드라마",19,미국
29,하우스,House,2004,8,44min,"드라마, 스릴러",15,미국
56,덱스터,Dexter,2006,8,53min,"범죄, 드라마, 스릴러",19,미국
61,길모어 걸스,Gilmore Girls,2000,8,46min,"코미디, 드라마",12,미국

In [45]:
drama['age_rating'].value_counts()

age_rating
15     419
19     272
12      63
15+     37
12+      5
ALL      4
7        3
Name: count, dtype: int64